import { Injectable } from '@angular/core';
import { Playlist } from './playlist';
import { User } from './user';

@Injectable({
  providedIn: 'root'
})
export class UserService {

  constructor() {
    // codigo pra requisitar um back e guardar info em cache
  }

  loggedUser:User={
    user_id:'1',
    profile_picture:'/assets/img/noProfilePicture.svg',
    name:'Carlos Eduardo',
    username:'Bananão',
    password:'12345',
    favorite_songs:[],
    playlists:[
      {
        idPlaylist:'1',
        playlist_name:'playlist1',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'2',
        playlist_name:'playlist2',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'3',
        playlist_name:'playlist3',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'4',
        playlist_name:'playlist4',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'5',
        playlist_name:'playlist5',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'6',
        playlist_name:'playlist6',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'7',
        playlist_name:'playlist7',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'8',
        playlist_name:'playlist8',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'9',
        playlist_name:'playlist9',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'10',
        playlist_name:'playlist10',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'11',
        playlist_name:'playlist11',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'12',
        playlist_name:'playlist12',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'13',
        playlist_name:'playlist13',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
      {
        idPlaylist:'14',
        playlist_name:'playlist14',
        image:'/assets/img/noPlaylistPicture.svg',
        musics:[
          'musica1',
          'musica2',
          'musica3',
          'musica4',
        ]
      },
    ]
  }
}
